import { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "oversize-hoodie-black",
    title: "Oversize Hoodie Black",
    description: "Плотное худи оверсайз кроя из тяжёлого хлопка.",
    price: 25000,
    oldPrice: 32000,
    images: ["/qala2.png"],
    category: "hoodies",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black"],
    stock: 12,
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "2",
    slug: "oversize-hoodie-white",
    title: "Oversize Hoodie White",
    description: "Плотное худи оверсайз кроя из тяжёлого хлопка.",
    price: 25000,
    images: ["/qala3.png"],
    category: "hoodies",
    sizes: ["S", "M", "L", "XL"],
    colors: ["white"],
    stock: 12,
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "3",
    slug: "t-shirt-white",
    title: "Oversize T-shirt White",
    description: "Футболка оверсайз.",
    price: 15000,
    oldPrice: 20000,
    images: ["/qala4.png"],
    category: "t-shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["white"],
    stock: 12,
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "4",
    slug: "t-shirt-white",
    title: "Oversize T-shirt White",
    description: "Футболка оверсайз.",
    price: 15000,
    oldPrice: 20000,
    images: ["/qalahood-logo.svg"],
    category: "t-shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["white"],
    stock: 12,
    createdAt: "2026-01-15T10:00:00Z",
  },
];
